/*
 * Nager.Date API - V3
 *
 * Nager.Date is open source software and is completely free for commercial use. If you would like to support the project you can award a GitHub star ⭐ or even better <a href='https://github.com/sponsors/nager'>actively support us</a>
 *
 * The version of the OpenAPI document: v3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CountryV3Dto : Country



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CountryV3Dto {
    #[serde(rename = "countryCode", skip_serializing_if = "Option::is_none")]
    pub country_code: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl CountryV3Dto {
    /// Country
    pub fn new() -> CountryV3Dto {
        CountryV3Dto {
            country_code: None,
            name: None,
        }
    }
}


