/*
 * Nager.Date API - V3
 *
 * Nager.Date is open source software and is completely free for commercial use. If you would like to support the project you can award a GitHub star ⭐ or even better <a href='https://github.com/sponsors/nager'>actively support us</a>
 *
 * The version of the OpenAPI document: v3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LongWeekendV3Dto : Long Weekend



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LongWeekendV3Dto {
    /// StartDate
    #[serde(rename = "startDate", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<String>,
    /// EndDate
    #[serde(rename = "endDate", skip_serializing_if = "Option::is_none")]
    pub end_date: Option<String>,
    /// DayCount
    #[serde(rename = "dayCount", skip_serializing_if = "Option::is_none")]
    pub day_count: Option<i32>,
    /// NeedBridgeDay
    #[serde(rename = "needBridgeDay", skip_serializing_if = "Option::is_none")]
    pub need_bridge_day: Option<bool>,
}

impl LongWeekendV3Dto {
    /// Long Weekend
    pub fn new() -> LongWeekendV3Dto {
        LongWeekendV3Dto {
            start_date: None,
            end_date: None,
            day_count: None,
            need_bridge_day: None,
        }
    }
}


