/*
 * Nager.Date API - V3
 *
 * Nager.Date is open source software and is completely free for commercial use. If you would like to support the project you can award a GitHub star ⭐ or even better <a href='https://github.com/sponsors/nager'>actively support us</a>
 *
 * The version of the OpenAPI document: v3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PublicHolidayV3Dto : Public Holiday



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PublicHolidayV3Dto {
    /// The date
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    /// Local name
    #[serde(rename = "localName", skip_serializing_if = "Option::is_none")]
    pub local_name: Option<String>,
    /// English name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// ISO 3166-1 alpha-2
    #[serde(rename = "countryCode", skip_serializing_if = "Option::is_none")]
    pub country_code: Option<String>,
    /// Is this public holiday every year on the same date
    #[serde(rename = "fixed", skip_serializing_if = "Option::is_none")]
    pub fixed: Option<bool>,
    /// Is this public holiday in every county (federal state)
    #[serde(rename = "global", skip_serializing_if = "Option::is_none")]
    pub global: Option<bool>,
    /// ISO-3166-2 - Federal states
    #[serde(rename = "counties", skip_serializing_if = "Option::is_none")]
    pub counties: Option<Vec<String>>,
    /// The launch year of the public holiday
    #[serde(rename = "launchYear", skip_serializing_if = "Option::is_none")]
    pub launch_year: Option<i32>,
    /// A list of types the public holiday it is valid
    #[serde(rename = "types", skip_serializing_if = "Option::is_none")]
    pub types: Option<Vec<crate::models::PublicHolidayType>>,
}

impl PublicHolidayV3Dto {
    /// Public Holiday
    pub fn new() -> PublicHolidayV3Dto {
        PublicHolidayV3Dto {
            date: None,
            local_name: None,
            name: None,
            country_code: None,
            fixed: None,
            global: None,
            counties: None,
            launch_year: None,
            types: None,
        }
    }
}


